<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<!--[if IE ]>
  <link href="iecss.css" rel="stylesheet" type="text/css">
<![endif]-->
<?php
$helper = $this->helper('Solwin\Cpanel\Helper\Data');
$showsocial = $helper->getShowsocialicons();

$baseUrl = $helper->getBaseUrl();
$mediaurl = $helper->getMediaUrl() . 'social/';
$f_logo = $helper->getFooterlogo();
$footer_logo = $mediaurl . $helper->getFooterlogo();
$helper = $this->helper('Solwin\Cpanel\Helper\Data');
$mediasocialurl = $helper->getMediaUrl() . 'social/';
$newsletter_title = $helper->getFooternewslettertitle();
$newsletter_text = $helper->getFooternewslettertext();
$newsletter_show = $helper->getShowfooternewsletter();
?>
<div class="page-footer">
    <div class="fs-main pad-main">
        <div class="page-main">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_our_services')->toHtml(); ?>
        </div>
    </div>
    <div class="page-main">
        <div class="cp-footer-container">
            <div class="cp-footer-main">
                <div class="cp-fblock">
                    <div class="cp-fcontent">
                        <?php if ($f_logo != '') { ?>
                            <a class="logo" href="<?php echo $baseUrl; ?>">
                                <img src="<?php echo $footer_logo; ?>" alt="Logo">
                            </a>
                        <?php } ?>
                        <?php
                        if ($showsocial) {
                            $showfacebook = $helper->getShowfacebook();
                            $showtwitter = $helper->getShowtwitter();
                            $showlinkedin = $helper->getShowlinkedin();
                            $showgoogle = $helper->getShowgoogle();
                            $showpinterest = $helper->getShowpinterest();
                            ?>
                            <ul class="cp-social">
                                <?php if ($showfacebook) { ?>
                                    <li><a href="<?php echo $helper->getFacebookurl(); ?>" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                <?php } ?>
                                <?php if ($showtwitter) { ?>
                                    <li><a href="<?php echo $helper->getTwitterurl(); ?>" target="_blank"><i class="fa fa-twitter"></i></a></li>
                                <?php } ?>
                                <?php if ($showlinkedin) { ?>
                                    <li><a href="<?php echo $helper->getLinkdnurl(); ?>" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                                <?php } ?>
                                <?php if ($showgoogle) { ?>
                                    <li><a href="<?php echo $helper->getGoogleurl(); ?>" target="_blank"><i class="fa fa-google-plus"></i></a></li>
                                <?php } ?>
                                <?php if ($showpinterest) { ?>
                                    <li><a href="<?php echo $helper->getPinteresturl(); ?>" target="_blank"><i class="fa fa-pinterest"></i></a></li>
                                <?php } ?>
                            </ul>
                        <?php } ?>
                    </div>
                </div>
            </div>
            <div class="cp-footer-main">
                <div class="cp-fblock">
                    <div class="cp-ftitle">
                        <h3>
                            <?php echo __('SUBSCRIBE US') ?>
                        </h3>
                    </div>
                    <div class="cp-fcontent">
                        <p class="footer-para">Lorem Ipsum is simply dummy text of the printing and typesetting industry.text of the printing and typesetting industry.</p>
                         <form>
                        <input type="email" name="Email" class="email" placeholder="Enter your email..." style="color:white;" required="">
                        <button class="btn1"><i class="fa fa-arrow-right" aria-hidden="true"></i></button>
                       
                    </form>
                    </div>
                </div>
            </div>
            <div class="cp-footer-main">
                <div class="cp-fblock">
                    <div class="cp-ftitle">
                        <h3>
                            <?php echo __('NAVIGATION') ?>
                        </h3>
                    </div>
                    <div class="cp-fcontent" style="margin-top: 6%;">
                        <ul>
                            <li>
                                <div class="cp-fcontact">
                                    <a href="#"><div><b>Home</b></div></a>
                                    <div><?php echo $helper->getContactstoreaddress(); ?></div>
                                </div>
                            </li>
                            <li>
                                <div class="cp-fcontact">
                                    <div><b><a href="#">About Us</a></b></div>
                                    <div><?php echo $helper->getStorecontactno(); ?></div>
                                </div>
                            </li>
                            <li>
                                <div class="cp-fcontact">
                                    <div><b><a href="#">Projects</a></b></div>
                                    <div><a href="mailto:<?php echo $helper->getStorecontactemail(); ?>"><?php echo $helper->getStorecontactemail(); ?></a></div>
                                </div>
                            </li>
                             <li>
                                <div class="cp-fcontact">
                                    <div><b><a href="#">Features</a></b></div>
                                    <div><a href="mailto:<?php echo $helper->getStorecontactemail(); ?>"><?php echo $helper->getStorecontactemail(); ?></a></div>
                                </div>
                            </li>
                             <li>
                                <div class="cp-fcontact">
                                    <div><b><a href="#">Contact Us</a></b></div>
                                    <div><a href="mailto:<?php echo $helper->getStorecontactemail(); ?>"><?php echo $helper->getStorecontactemail(); ?></a></div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="cp-footer-main">
                <div class="cp-fblock">
                    <div class="cp-ftitle">
                        <h3>
                            <?php echo __('CONTACT US') ?>
                        </h3>
                    </div>
                    <div class="cp-fcontent">
                        <div class="contactt">
                            <div class="icon-div6">
                                <i class="fa fa-envelope ico6"></i>
                                 <p class="vide1">info@example.com</p>
                            </div>
                        <div class="icon-div6">
                            <i class="fa fa-phone ico6"></i>
                            <p class="vide"> +1(23) 4567 890</p>
                        </div>
                        <div class="icon-div6">
                            <i class="fa fa-home ico6"></i>
                            <p class="vide">Lorem Ipsum is simply
                            <br> dummy text of the printing</p>
                        </div>
                        </div>  
                    </div>
                </div>
            </div>
            <div class="cp-footer-main">
                <div class="cp-fblock">
                    <div class="cp-ftitle">
                        <h3>
                            <?php echo __('GET IN TOUCH') ?>
                        </h3>
                    </div>
                    <div class="cp-fcontent">
                       
                                <div class="cp-fcontact">
                                   <p class="footer-para">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                                </div>

    
                            <div class="social">
                              <ul >
                                <li class="color22">
                                    <div class="circle1"><i class="fa fa-facebook-f color221" aria-hidden="true"></div></i></li>
                                <li class="color23">
                                    <div class="circle1"><i class="fa fa-twitter color221" aria-hidden="true"></div></i></li>
                                <li class="color24">
                                    <div class="circle1"><i class="fa fa-instagram color221" aria-hidden="true"></div></i></li>
                                <li class="color25">
                                    <div class="circle1"><i class="fa fa-linkedin color221" aria-hidden="true"></div></i></li>
                              </ul>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
$enable = $helper->getShowsharingaddon();
$pubid = $helper->getAddthispubid();

if ($enable) {
    ?>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=<?php echo $pubid; ?>" async="async"></script>
<?php } ?>
